<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:44:21 -0700
return array(
    'LmcUserDoctrineMongoODM\Module'                            => __DIR__ . '/Module.php',
    'LmcUserDoctrineMongoODM\Document\User'                     => __DIR__ . '/src/LmcUserDoctrineMongoODM/Document/User.php',
    'LmcUserDoctrineMongoODM\Document\UserMappedSuperClass'     => __DIR__ . '/src/LmcUserDoctrineMongoODM/Document/UserMappedSuperClass.php',
    'LmcUserDoctrineMongoODM\Event\ResolveTargetEntityListener' => __DIR__ . '/src/LmcUserDoctrineMongoODM/Event/ResolveTargetEntityListener.php',
    'LmcUserDoctrineMongoODM\Mapper\UserMongoDb'                => __DIR__ . '/src/LmcUserDoctrineMongoODM/Mapper/UserMongoDb.php',
    'LmcUserDoctrineMongoODM\Options\ModuleOptions'             => __DIR__ . '/src/LmcUserDoctrineMongoODM/Options/ModuleOptions.php'
);